# Generated by Django 3.0.5 on 2020-08-05 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
    ]
