# Generated by Django 3.0.5 on 2020-08-05 16:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200805_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion de la habilidad')),
                ('percentage', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
