# Generated by Django 3.0.5 on 2020-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Url del video')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name': 'Halilidad', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
