# Generated by Django 3.0.5 on 2020-08-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200805_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='Projects/author', verbose_name='Imagen Autor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
