# Generated by Django 3.0.5 on 2020-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='color',
            field=models.CharField(default='color-1', max_length=100, verbose_name='Color'),
        ),
    ]
