# Generated by Django 3.0.5 on 2020-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200825_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='another',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='another'),
        ),
    ]
