# Generated by Django 3.0.5 on 2020-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200825_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='delay',
            field=models.CharField(blank=True, default='100ms', max_length=100, null=True),
        ),
    ]
