# Generated by Django 3.0.5 on 2020-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='filter_search',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Filtro'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
