# Generated by Django 3.0.5 on 2020-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200825_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='result',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
