# Generated by Django 3.0.5 on 2020-08-26 16:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200825_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo de texto')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Contenido de texto')),
                ('url', models.URLField(verbose_name='Url del video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='video', verbose_name='Imagen video')),
            ],
        ),
    ]
