# Generated by Django 3.0.5 on 2020-08-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200826_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fijo',
            field=models.CharField(default=0, max_length=100, verbose_name='Numero de Contacto'),
        ),
    ]
