# Generated by Django 3.0.5 on 2020-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contact_fijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='icon',
            field=models.CharField(max_length=20, verbose_name='Icono'),
        ),
    ]
