# Generated by Django 3.0.5 on 2020-08-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200826_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='important_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo Importante'),
        ),
    ]
