# Generated by Django 3.0.5 on 2020-08-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_project_important_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='important_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo Importante'),
        ),
    ]
