# Generated by Django 3.0.5 on 2020-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200826_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='logros')),
                ('relation', models.CharField(max_length=200, verbose_name='carrera')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='achievements',
            field=models.ManyToManyField(to='core.Achievements', verbose_name='logros'),
        ),
    ]
