# Generated by Django 3.0.5 on 2020-08-26 21:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_career_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=300, verbose_name='Descripción de la elección'),
        ),
    ]
